env:
  browser: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  array-bracket-spacing:
    - error
    - never
  array-element-newline:
    - error
    - consistent
  arrow-spacing:
    - error
    - before: true
      after: true
  block-scoped-var:
    - error
  block-spacing:
    - error
    - always
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  camelcase:
    - error
  class-methods-use-this:
    - error
  comma-dangle:
    - error
  comma-spacing:
    - error
  comma-style:
    - error
    - first
  complexity:
    - warn
    - 20
  computed-property-spacing:
    - error
    - never
  curly:
    - error
    - all
  default-case-last:
    - error
  default-param-last:
    - error
  dot-location:
    - error
    - property
  dot-notation:
    - error
  eol-last:
    - error
  eqeqeq:
    - error
    - smart
  func-call-spacing:
    - error
    - never
  func-style:
    - error
    - declaration
  function-call-argument-newline:
    - error
    - consistent
  function-paren-newline:
    - error
    - multiline
  grouped-accessor-pairs:
    - error
  implicit-arrow-linebreak:
    - error
    - beside
  indent:
    - error
    - 2
  init-declarations:
    - error
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
      mode: strict
  keyword-spacing:
    - error
    - before: true
      after: true
  linebreak-style:
    - error
    - unix
  lines-between-class-members:
    - error
    - always
  max-depth:
    - warn
    - 4
  max-len:
    - warn
    - 120
  new-cap:
    - error
  new-parens:
    - error
    - always
  no-array-constructor:
    - error
  no-console:
    - warn
  no-constructor-return:
    - error
  no-duplicate-imports:
    - error
  no-else-return:
    - error
  no-empty-function:
    - error
  no-eval:
    - error
  no-extend-native:
    - error
  no-extra-label:
    - error
  no-extra-parens:
    - error
    - all
  no-floating-decimal:
    - error
  no-implicit-coercion:
    - error
  no-implicit-globals:
    - error
  no-implied-eval:
    - error
  no-invalid-this:
    - error
  no-iterator:
    - error
  no-labels:
    - error
  no-label-var:
    - error
  no-lone-blocks:
    - error
  no-lonely-if:
    - error
  no-loop-func:
    - error
  no-loss-of-precision:
    - error
  no-magic-numbers:
    - warn
    - ignore: []
      ignoreArrayIndexes: true
  no-mixed-operators:
    - error
  no-multi-assign:
    - error
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 0
      maxBOF: 0
  no-multi-spaces:
    - error
  no-multi-str:
    - error
  no-negated-condition:
    - error
  no-nested-ternary:
    - error
  no-new:
    - error
  no-new-func:
    - error
  no-new-object:
    - error
  no-new-wrappers:
    - error
  no-nonoctal-decimal-escape:
    - error
  no-octal-escape:
    - error
  no-param-reassign:
    - error
  no-proto:
    - error
  no-promise-executor-return:
    - error
  no-return-assign:
    - error
  no-return-await:
    - error
  no-script-url:
    - error
  no-self-compare:
    - error
  no-sequences:
    - error
  no-shadow:
    - error
  no-tabs:
    - error
  no-throw-literal:
    - error
  no-trailing-spaces:
    - error
  no-undef-init:
    - error
  no-undefined:
    - error
  no-underscore-dangle:
    - error
  no-unmodified-loop-condition:
    - warn
  no-unneeded-ternary:
    - error
  no-unused-expressions:
    - error
  no-unreachable-loop:
    - error
  no-unsafe-optional-chaining:
    - error
  no-useless-backreference:
    - error
  no-useless-call:
    - error
  no-useless-computed-key:
    - error
    - enforceForClassMembers: true
  no-useless-concat:
    - error
  no-useless-return:
    - error
  no-var:
    - error
  no-void:
    - error
  no-warning-comments:
    - warn
  no-whitespace-before-property:
    - error
  object-curly-newline:
    - error
    - multiline: true
  object-curly-spacing:
    - error
    - never
  object-property-newline:
    - error
  object-shorthand:
    - error
    - always
  one-var:
    - error
    - never
  operator-assignment:
    - error
    - always
  operator-linebreak:
    - error
    - before
  padded-blocks:
    - error
    - never
  prefer-arrow-callback:
    - error
  prefer-const:
    - error
  prefer-exponentiation-operator:
    - error
  prefer-object-spread:
    - error
  prefer-promise-reject-errors:
    - error
  prefer-regex-literals:
    - error
  prefer-rest-params:
    - error
  prefer-spread:
    - error
  quote-props:
    - error
    - consistent-as-needed
  quotes:
    - error
    - single
  radix:
    - error
    - as-needed
  require-await:
    - error
  rest-spread-spacing:
    - error
    - never
  semi:
    - error
    - always
  semi-spacing:
    - error
    - before: false
      after: true
  semi-style:
    - error
    - last
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - never
  space-in-parens:
    - error
    - never
  space-infix-ops:
    - error
  spaced-comment:
    - error
    - always
  switch-colon-spacing:
    - error
    - after: true
      before: false
  template-curly-spacing:
    - error
    - never
  unicode-bom:
    - error
    - never
  yoda:
    - error
    - always
